language: ruby
addons:
  sonarcloud:
    organization: unbouncerabbit-github
    token:
      secure: "Fefo0uAbYDdMBjUtUHS2n3wk2usuQCZxGhii4jOTDUHk50DZ4sgvAfxPHN5RN+f9FG2mwgJzi5rJINhXqpwTY7T846jPgCbOaihSOrk9H7bWTQ/K5HxWakr1F6x/frZc463YST61SiI0PFsu+oPBwA/tZ9fS8un3is8bYgZbkgw="
script:
  - bundle exec rake spec
  - gem build recurly.gemspec
  - sonar-scanner
cache: bundler
sudo: false
rvm:
  - jruby
  - jruby-9000
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.4
  - 2.3.0
  - 2.4.0
env:
  - XML=rexml
  - XML=nokogiri
matrix:
  allow_failures:
    - rvm: 1.9.3
      env: XML=nokogiri
    - rvm: 2.0.0
      env: XML=nokogiri
    - rvm: jruby
      env: XML=nokogiri
